### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an HTML document that contains a `div` for the car.
- [x] Insert image of car into div.
- [x] Create a CSS document that styles page.
- [x] Ensure that all styling is correct.
- [x] Remove any unnecessary styling.
