### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add CSS rotate functions to `styles.css` so that the car will turn the equivalent amount of degrees for north, south, east, and west.
- [x] In `main.js`, add an event listener that listens for keydown events when the arrow keys are pushed.
- [x] In `main.js`, add conditions that make the car rotate with the corresponding arrow that is pressed.
- [x] Double check that all functionality is working properly.
- [x] Remove all unnecessary styling.
