### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Create a function that increments the position of the car on the x-axis by 1 so that the car moves from left to right.
- [x] Create an event listener that makes the car move every 16 milliseconds when the spacebar is pressed.
- [x] Double check that the functionality is working correctly.
- [x] Remove all unnecessary code and styling.
