### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] Add a clearInterval method to the main.js that initiates when the spacebar is pressed.  This should make the car stop.
- [ ] Make the car continue moving when the spacebar is pressed again.  
- [ ] If the car does not stop, it continues off the screen.
- [ ] Double check that all functionality is working correctly.
- [ ] Remove all unnecessary code and styling.
